const defaultConfig = {
  ip: [192, 168, 8, 40],
  mask: [255, 255, 255, 0],
  gateway: [null, null, null, null],
  mac: 'E8-DE-27-B0-AA-AB',
  timeSource: 'Manual',
  currentDate: 0,
  currentTime: '00:00:00',
  timeZone: '',
  firstNTP: [null, null, null, null],
  secoundNTP: [null, null, null, null],
  updateRate: 0,
  firmware: '1.0.0 Build 20140126 Rel.34563',
  hardware: 'TL-SG2008 1.0',
  deviceName: 'TL-SG2008',
  systemContact: 'www.tp-link.com',
  deviceLocation: 'SHENZEN',
  dstStatus: 'Enable',
  dstSource: 'PredefinedMode',
  predefinedMode: 'Europe',
  dstDateModeOffset: undefined,
  dstDateModeStart: undefined,
  dstDateModeEnd: undefined,
  dstRecurringModeStart: undefined,
  dstRecurringModeEnd: undefined,
  dstRecurringModeOffset: undefined,
  addressMode: 'Static IP',
  managmentVlan: '1',
  users: [
    { username: 'admin', password: 'admin', permission: 'Admin' },
    {
      username: 'Jarek',
      password: 'admin',
      permission: 'Guest',
    },
  ],
  telnetEnabled: 'disabled',
  //SSH-START
  sshStatus: 'Disable',
  protocolv2SSH: 'Disable',
  protocolv1SSH: 'Disable',
  idleTimeoutSSH: undefined,
  maxConnectSSH: undefined,
  encryptionAlgorithm: [
    'AES128-CBC',
    'AES192-CBC',
    'AES256-CBC',
    'Blowfish-CBC',
    'Cast128-CBC',
    '3DES-CBC',
  ],
  dataIntegrityAlgorithm: ['HMAC-SHA1', 'HMAC-MD5'],
  keyType: '',
  //SSH-END
  httpStatus: 'Enable',
  sessionTimeoutHTTP: '30',
  numberControlHTTP: 'Disable',
  adminNumberHTTP: undefined,
  guestNumberHTTP: undefined,
  httpsStatus: 'Enable',
  sslVersionHTTPS: 'Enable',
  tlsVersionHTTPS: 'Enable',
  cipherSuite1HTTPS: 'Enable',
  cipherSuite2HTTPS: 'Enable',
  cipherSuite3HTTPS: 'Enable',
  cipherSuite4HTTPS: 'Enable',
  sessionTimeoutHTTPS: '30',
  numberControlHTTPS: undefined,
  adminNumberHTTPS: undefined,
  guestNumberHTTPS: undefined,
  portConfig: [
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: 'LAG1',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: 'LAG1',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
    {
      description: '',
      status: 'Enable',
      speed: 'Auto',
      flow: 'Disable',
      lag: '---',
    },
  ],
  mirrorList: [
    {
      group: 1,
      mirroring: 0,
      mirroredPortIngress: [],
      mirroredPortEgress: [],
    },
    {
      group: 2,
      mirroring: 0,
      mirroredPortIngress: [],
      mirroredPortEgress: [],
    },
    {
      group: 3,
      mirroring: 0,
      mirroredPortIngress: [],
      mirroredPortEgress: [],
    },
    {
      group: 4,
      mirroring: 0,
      mirroredPortIngress: [],
      mirroredPortEgress: [],
    },
  ],
  portSecurityConfig: [
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
    {
      maxLearnedMAC: 64,
      learnedNum: 0,
      learnMode: 'Dynamic',
      status: 'Disable',
    },
  ],
  portIsolationConfig: [
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, false, false, false, false, false] },
    { forwardList: [false, false, false, true, false, false, false, false] },
  ],
  portLoopbackGlobal: {
    detection: 'enabled',
    interval: 2,
    automaticRecovery: 60,
    webRefresh: 'disabled',
    webInterval: 3,
  },
  portLoopback: [
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: 'LAG1',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: 'LAG1',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
    {
      status: 'Enable',
      operationMode: 'Port Based',
      recoveryMode: 'Auto',
      loopStatus: '---',
      blockStatus: '---',
      LAG: '---',
    },
  ],
  addressTableConfig: {
    firstEdit: '123',
    table: {
      names: [
        'Port',
        'Description',
        'Status',
        'SpeedAndDuplex',
        'FlowControl',
        'LAG',
      ],
      fields: [
        { type: 'disable' },
        { type: 'text' },
        { type: 'select', options: ['Enable', 'Disable'] },
        { type: 'select', options: ['Auto', '10MHD'] },
        { type: 'select', options: ['Enable', 'Disable'] },
        { type: 'disable' },
      ],
      data: [
        ['1', 'Szczur1', 'Disable', 'Auto', 'Enable', 'LAG1'],
        ['2', 'Szczur2', 'Enable', 'Auto', 'Disable', 'LAG1'],
        ['3', 'Szczur3', 'Disable', 'Auto', 'Enable', undefined],
        ['4', 'Szczur4', 'Enable', 'Auto', 'Disable', undefined],
        ['5', 'Szczur5', 'Disable', 'Auto', 'Enable', undefined],
        ['6', 'Szczur6', 'Enable', 'Auto', 'Disable', undefined],
        ['7', 'Szczur7', 'Enable', 'Auto', 'Disable', 'LAG1'],
        ['8', 'Szczur8', 'Enable', 'Auto', 'Disable', 'LAG1'],
      ],
    },
  },
};

export default defaultConfig;
